name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@main

      - name: ⬇️ Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.1
        with:
          browser: chrome
          component: true
